### PR TITLE
Support for default values for attributes

### PR DESCRIPTION
**Pull request by georgebina**

### CODE REVIEW

**Comment by jelovirt** [comment]
Are there any plans to merge this feature?

**Comment by georgebina** [comment]
@jclark maybe you can look over the proposed changes? This are useful in context of DITA 1.3, starting with version 1.3 DITA uses Relax NG as main schema language.

**Comment by georgebina** [comment]
I just enabled edits.

**Comment by sideshowbarker** [comment]
> I just enabled edits.

OK, I've reviewed the code changes and tested it the best I can within the limits of my understanding of how it should work.

I still think it’d be better to include a test in the patch before we merge it — but if you’d prefer we not block on that but instead go ahead and merge it to master as-is (and include it in the release), then just lemme know and I’ll merge it and tag and build the release.

**Pull request merged**
