### PR TITLE
Implement XML 1.0 Fifth Edition updates to naming.

### PR DESCRIPTION
**Pull request by georgebina**
Suggested fix for #188 - implements the XML 5th edition updates to allowed naming characters http://www.w3.org/TR/REC-xml/#NT-NameStartChar

### CODE REVIEW

**Comment by georgebina** [comment]
I see that the tests fail after this change... so we need to look into this as well.

**Comment by georgebina** [comment]
The problems reported by the tests are:
```mod.rng-validate.test-spec:
     [java] Failed: /Users/george/Documents/workspace/jing-trang-github/build/mod/rng-validate/test-spec/070/i.rng
     [java] Failed: /Users/george/Documents/workspace/jing-trang-github/build/mod/rng-validate/test-spec/072/i.rng
     [java] Failed: /Users/george/Documents/workspace/jing-trang-github/build/mod/rng-validate/test-spec/073/i.rng
     [java] Failed: /Users/george/Documents/workspace/jing-trang-github/build/mod/rng-validate/test-spec/074/i.rng
     [java] Failed: /Users/george/Documents/workspace/jing-trang-github/build/mod/rng-validate/test-spec/079/i.rng
     [java] Number of tests: 965
     [java] Elapsed time: 781
```
which seem to check the 0x0e35 as a name start character - and now this is allowed, being in the range `[#x37F-#x1FFF]` from the NameStartChar production.

**Comment by georgebina** [comment]
The commit 863639cc1a9dc58b3217592171dc8d48cc8dca0b removes the failing tests that check the 0x0e35 as a name start character.

**Comment by sideshowbarker** [comment]
When I rebase this branch against master and run `./ant test` I get test failures:

```
mod.regex.test-naming:
     [java] Failed for 132; expected name == true
…
     [java] 38493 tests failed

BUILD FAILED
/private/tmp/jing-trang/build.xml:48: The following error occurred while executing this line:
/private/tmp/jing-trang/modbuild.xml:1042: Java returned: 1
```

**Comment by sideshowbarker** [comment]
Closing this as stale and still broken per https://github.com/relaxng/jing-trang/pull/204#pullrequestreview-170721526. Easy enough to just reopen if anything changes.

**Pull request closed without merging**
