### PR TITLE
Initial Japanese localization

### PR DESCRIPTION
**Pull request by tgraham-antenna**
Translated by someone who is not a native RELAX NG speaker.

Should also be checked by a native Japanese speaker.

`jing.jar` builds okay, and Japanese messages are usable with oXygen 17.1 and with standalone **focheck**.

### CODE REVIEW

**Comment by AirQuick** [comment]
I guess they came from machine translation. The translation quality is surprisingly poor. Some are incorrect. Some sound like joking.

**Comment by sideshowbarker** [comment]
> I guess they came from machine translation. The translation quality is surprisingly poor. Some are incorrect. Some sound like joking.

If they’re bad enough to the point that we should revert this change — that is, if it’s worse to have these translations than to have none at all — then I will revert this change. Lemme know.

**Comment by AirQuick** [comment]
Definitely worth reverting, unless you want to be as funny as _All your base are belong to us_.

**Comment by AirQuick** [comment]
Unfortunately the current translation is no better than machine translation. I'm afraid you would rather have to translate from scratch than to try improving it.

**Comment by sideshowbarker** [comment]
OK, reverted in 051a5f3

**Pull request merged**
