### PR TITLE
pull request: compile with java 11

### PR DESCRIPTION
**Pull request by aanno**
When I try to compile relaxng/jing-trang branch master with java 11, I get the following error:

```
BUILD FAILED
/home/tpasch/scm/github/jing-trang/build.xml:43: java.lang.ClassNotFoundException: com.icl.saxon.TransformerFactoryImpl
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
```
My pull request fixes the problem by:
* removing the (build) dependency on the (old) com.icl.saxon: The ant build now only uses the modern saxon9 jar (net.sf.saxon)

In addition I tackled the following:
* build is now for java8 (as java7 is long gone)
* added a gradle build file (that only imports the ant build): This way, the project becomes easier to  use in/with other gradle builds (as composite build or sub project)
  + But for this to work, I had to rename some of the ant tasks a bit:
     - init -> ant-init
     - jar -> ant-jar
     - clean -> ant-clean
     - javadoc -> ant-javadoc

I would be very glad if you could consider integration into the master branch.

Kind regards,

aanno

### CODE REVIEW

**Comment by aanno** [comment]
I updated my gradle build file (`build.gradle.kts`) a bit. 

I would like to repeat is that gradle stuff is completely optional, i.e. I would remove it from the PR if there are concerns.

**Comment by ndw** [comment]
This seems fine to me, @sideshowbarker do you have concerns?

**Comment by aanno** [comment]
Well, thank you for feedback. 

For me it's rather strange that you never encountered a ClassNotFoundException on builds - because it happens to me _every_ time. As an informed guess, I would throw suspect on a classpath issue.

What I actually did is to remove the (very old) saxon.jar and use the (already present) saxon9.jar as replacement. For me it looks like that saxon.jar was only used for _building_ the project.

I now thinks that is not true: there is the `OldSaxonSchemaReaderFactory` that uses the old saxon (package ns `com.icl.saxon`) while NewSaxonSchemaReaderFactory uses saxon9 (package ns `net.sf.saxon`).

So it boils down to (a) if there is still any need to support the aged saxon and (b) find a convincing argument why having both saxon on classpath could lead to ClassNotFoundException with java 11.

I completly agree that the PR needs separation of the gradle stuff.

**Comment by sideshowbarker** [comment]
> For me it's rather strange that you never encountered a ClassNotFoundException on builds - because it happens to me _every_ time.

What OS distro are on testing on? Yesterday at https://github.com/validator/validator/pull/744#issuecomment-455121060 I got a report of a ClassNotFoundException that seems to happen only on Fedora with the openjdk11 package.

Do you have multiple OS distros you’re able to test on? And if so can you reproduce the ClassNotFoundException on those?

We currently have data to indicate the ClassNotFoundException problem reported here isn’t reproducible in the default Java environment on MacOS with openjdk11, nor on Ubuntu with openjdk11, oraclejdk11, openjdk10, oraclejdk9, or openjdk-ea (=12) — because those are what our Travis CI tests.

> As an informed guess, I would throw suspect on a classpath issue.

Yes I can vaguely understand that it must be related somehow to the Modules feature introduced in Java 9 — and thus maybe the underlying issue reported at https://github.com/relaxng/jing-trang/issues/246 — but I personally don’t have any experience so far in trying to troubleshoot and fix any problems related to that.

And regardless, I would expect that whatever difference were caused by the Modules feature, we’d consistently run into those problems no matter what OS distro we ran the build on.

So the only wild guess I can personally come up with at this point is that maybe in some environments (e.g., Fedora) the OS distro packagers/maintainers have the openjdk11 package configured (and maybe the openjdk10 and openjdk9 packages) to flip on some non-default Java environment setting related to Modules that breaks backward compatibility. 

> I now thinks that is not true: there is the `OldSaxonSchemaReaderFactory` that uses the old saxon (package ns `com.icl.saxon`) while NewSaxonSchemaReaderFactory uses saxon9 (package ns `net.sf.saxon`).

Right

**Comment by unkannan** [comment]
a

**Comment by aanno** [comment]
Closed in favour of #255

**Pull request closed without merging**
